# Project Name
TARGET = resonate

# Sources
CPP_SOURCES = main.cpp \
engine.cpp \
hw/daeisy_shield.cpp

# Library Locations
LIBDAISY_DIR = ../lib/libdaisy
DAISYSP_DIR = ../lib/daisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
include ../common/Makefile
