# Project Name
TARGET = jackoscillator

CPP_SOURCES =
CPP_SOURCES += \
src/main.cpp \
src/dsp/WTFOscillator.cpp

# Library Locations
LIBDAISY_DIR = $(PWD)/lib/libdaisy
DAISYSP_DIR = $(PWD)/lib/DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
