# Project Name
TARGET = jackoscillator

CPP_SOURCES =
CPP_SOURCES += \
src/main.cpp \
src/dsp/WTFOscillator.cpp \
src/hw/daeisy_shield.cpp

# Library Locations
LIBDAISY_DIR = ../lib/libdaisy
DAISYSP_DIR = ../lib/daisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
